name: Actualizar precio del dólar

on:
  schedule:
    - cron: "*/15 * * * *"  # cada 15 minutos
  workflow_dispatch:

jobs:
  update_dolar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python3 dolar_selenium.py

      - name: Checkout gh-pages branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Copy updated JSON to gh-pages
        run: |
          cp dolarbolivia.json ../dolarbolivia.json
          git add dolarbolivia.json

      - name: Commit and push changes to gh-pages
        run: |
          git commit -m "🔁 Actualizar precio dólar" || echo "No hay cambios"
          git push origin gh-pages

      - name: Switch back to main branch
        run: git checkout main
