name: Actualizar precio del dólar

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar todas las ramas
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Instalar dependencias
        run: |
          pip install selenium webdriver-manager

      - name: Cambiar a main y ejecutar script
        run: |
          git switch main
          python3 dolar_selenium.py

      - name: Cambiar a gh-pages y mover JSON
        run: |
          git switch gh-pages
          cp ../dolarbolivia.json .
          cp ../historial_dolarbolivia.json .

      - name: Hacer commit y push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json historial_dolarbolivia.json
          git commit -m "⏱ Actualización automática del dólar (hora Bolivia)" || echo "Sin cambios que commitear"
          git push origin gh-pages
