name: Actualizar precio del dólar

on:
  schedule:
    - cron: "*/15 * * * *"  # cada 15 minutos
  workflow_dispatch:

jobs:
  update_dolar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: |
          pip install selenium webdriver-manager

      - run: python dolar_selenium.py

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json
          git commit -m "🔁 Actualizar precio dólar" || echo "Sin cambios"
          git push
