name: Actualizar precio del dólar

on:
  schedule:
     - cron: '0,5,10,15,20,25,30,35,40,45,50,55 * * * *'  # cada 5 minutos exactos
  workflow_dispatch:

jobs:
  actualizar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Cambiar a gh-pages
      run: git switch gh-pages

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: pip install selenium webdriver-manager

    - name: Ejecutar script Python
      run: python dolar_selenium.py

    - name: Commit y push a gh-pages
      run: |
        git add dolarbolivia.json historial_dolarbolivia.json
        git commit -m "✅ Actualización automática del precio del dólar" || echo "Sin cambios que commitear"
        git push origin gh-pages
