name: Actualizar precio del dólar

on:
  schedule:
    - cron: "*/15 * * * *"  # cada 15 minutos
  workflow_dispatch:

jobs:
  update_dolar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python dolar_selenium.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json
          git commit -m "🔁 Actualizar precio dólar" || echo "Sin cambios"
          git push origin gh-pages
