name: Actualizar precio del dólar

on:
  schedule:
    - cron: "*/5 * * * *"  # cada 5 minutos
  workflow_dispatch:

jobs:
  update_dolar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python3 dolar_selenium.py

      - name: Save JSONs to temporary location
        run: |
          cp dolarbolivia.json /tmp/dolarbolivia.json
          cp historial_dolarbolivia.json /tmp/historial_dolarbolivia.json

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Move JSONs into gh-pages branch
        run: |
          cp /tmp/dolarbolivia.json dolarbolivia.json
          cp /tmp/historial_dolarbolivia.json historial_dolarbolivia.json
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json historial_dolarbolivia.json
          git commit -m "🔁 Actualizar precio dólar" || echo "No hay cambios"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
