name: Actualizar precio del dólar

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Cada hora

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar rama gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Instalar dependencias de Python
        run: |
          pip install selenium webdriver-manager

      - name: Ejecutar script para generar archivos JSON
        run: python3 dolar_selenium.py

      - name: Commit y push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json historial_dolarbolivia.json
          if ! git diff --cached --quiet; then
            git commit -m "Actualizar archivos JSON desde script Python"
            git push origin gh-pages
          else
            echo "No hay cambios que subir."
