name: Actualizar precio del dólar

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 5 minutos
  workflow_dispatch:

jobs:
  actualizar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # importante para cambiar de rama

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Instalar dependencias
      run: pip install selenium webdriver-manager

    - name: Ejecutar script Python
      run: python dolar_selenium.py

    - name: Configurar git y commitear archivos JSON
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add dolarbolivia.json historial_dolarbolivia.json
        git commit -m "Actualizar archivos JSON desde script Python" || echo "Nada que commitear"

    - name: Cambiar a gh-pages
      run: git switch gh-pages

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit y Push
      run: |
        git add dolarbolivia.json historial_dolarbolivia.json
        git commit -m "✅ Actualización automática del precio del dólar" || echo "Sin cambios que commitear"
        git push origin gh-pages
