name: Actualizar precio del dólar

on:
  schedule:
    # se ejecuta cada 5 minutos
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update_dolar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run scraper
        run: python dolar_selenium.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Copy updated JSON files
        run: |
          cp ../dolarbolivia.json ./dolarbolivia.json
          cp ../historial_dolarbolivia.json ./historial_dolarbolivia.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dolarbolivia.json historial_dolarbolivia.json
          git commit -m "🔁 Actualizar precio e historial del dólar" || echo "Sin cambios"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git gh-pages
