name: Actualizar precio del dólar

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 5 minutos
  workflow_dispatch:

jobs:
  actualizar-json:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # importante para cambiar de rama

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Instalar dependencias
      run: pip install selenium webdriver-manager

    - name: Ejecutar script Python
      run: python dolar_selenium.py

    - name: Cambiar a gh-pages
      run: git switch gh-pages

    - name: Copiar archivos JSON generados
      run: |
        cp ../dolarbolivia.json ./dolarbolivia.json
        cp ../historial_dolarbolivia.json ./historial_dolarbolivia.json

    - name: Configurar Git
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Commit y Push
      run: |
        git add dolarbolivia.json historial_dolarbolivia.json
        git commit -m "✅ Actualización automática del precio del dólar" || echo "Sin cambios que commitear"
        git push origin gh-pages
